# Generated by Django 2.0.5 on 2018-09-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.IntegerField()),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellido_P', models.CharField(max_length=200)),
                ('Apellido_M', models.CharField(max_length=200)),
                ('Tel', models.IntegerField()),
            ],
        ),
    ]
